### ISSUE TITLE
Populate Tab/Details view with Metadata processed from dataset

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/sds-viewer#17]
Tabular View Component is already created showing mock data. The goal of this card is to have display the appropriate metadata coming from the processed dataset and path-metadata json file.

User Story : 
As a user, I want to View metadata and protocol information of each dataset, so I can View metadata and protocol information of each dataset on its own tab .
![image](https://user-images.githubusercontent.com/4562825/123681690-f5c62280-d7fe-11eb-9d35-e1503a58befb.png)

**Comment by jrmartin** [comment]
List of properties to display for each node type. 
![image.png](https://images.zenhubusercontent.com/5b8f86ce39827c509079f60a/60c91815-914c-4808-87ae-233d07a74148)

Taken from https://docs.google.com/spreadsheets/d/1TZOzMKjzQYW98E_n4GZE_5PTnhVu3I2c-GmDdeNt0Os/edit#gid=921124134

**Comment by jrmartin** [comment]
Hi @ddelpiano .

Some of the feedback after today's sprint call.

- Node viewer component showing sections with ‘Details’ as header. Instead, let's show it more explicit as in : ‘Sample Details’ , 'Dataset Details' and ‘Subject Details.
![image](https://user-images.githubusercontent.com/4562825/134249552-3ab82888-da5d-4983-ab72-949c21850dcc.png)

- Let's leave the primary folders/collections out of the Node viewer, so that means not showing the 'Details' for the 'Subjects' folder or the 'Samples' folder.
![image](https://user-images.githubusercontent.com/4562825/134249518-5553bbb0-3098-4da8-87b1-d19e924abafa.png)

- On one of the 'Details' section, we have a scrollbar accross the Y axes, we should remove this. 
![image](https://user-images.githubusercontent.com/4562825/134249472-69676f86-5cba-4cde-984b-374ac48abbab.png)

- Anchors to be visible in metadata component at all times when scrolling. If the user scroll down the page, the anchors should still be visible. So maybe have them with posiiton 'fixed' to stick to page.

- Invert the order of the metadata component Details. If the user clicks on a file, the order on the metadata component should be : Dataset, Subject , Sample, File 

- Display all properties for the subject and sample  in metadata viewer
