### ISSUE TITLE
Create Hierarchical View Component

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/sds-viewer#44]
Create Hierarchical View Component
![image](https://user-images.githubusercontent.com/4562825/123681320-8b14e700-d7fe-11eb-8e74-86c4753811f5.png)

Search Bar: 
Search for certain named entities in hierarchical view. 

Dataset List:
List of uploaded datasets, each one containing subfolders and files. User wants to be able to vavigate datasets as if using the system's file explorer.

Import New Dataset:
Create UI component to upload local and external datasets https://github.com/MetaCell/sds-viewer/issues/43

**Comment by jrmartin** [comment]
@tgbugs How would you prefer the search to work in the Hierarchical View? 

When the user performs a search, we can update the component to display only those results within the loaded datasets (if any) that match the search. 
Or, we keep all the contents of the loaded datasets visible in the hierarchical view, and we highlight the results that match the search.

**Comment by tgbugs** [comment]
A couple of ideas, of which I think option 3 is probably the best (your option 2).

1. highlight matches and move them to the top of the list, keeping the parent paths visible
2. highlight matches and jump to the first match, have next/prev buttons for other matches, do not reorder
3. hide things that don't match, but only start hiding after the 3rd letter is typed or the user hits enter to execute the search, continue to show the parent folders for context (I think is essentially what you are proposing as your section option)

I initially thought that option 2 was better because short substring matches will lead to massive an annoying reorganization. However after a bit more thought ctrl-f already exists for just highlighting things on the page, so having the search box actually filter down the contents of the view as in option 3 is preferable.

**Comment by jrmartin** [comment]
Thanks @tgbugs, we'll proceed with option 3.
