### ISSUE TITLE
UI cul de sac import

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/sds-viewer#53]
Right now when I import a dataset from the local filesystem, either I import all the file at once from the same folder in the file system, differently if I import first the json or the turtle then I don't have a way to import an additional file.

Assigning this to you Jesus to discuss first the design change and the allocate in a sprint. Thx

**Comment by jrmartin** [comment]
Good catch, both files must be imported at the same time for it to work. 

We should allow the user to keep uploading after uploading the first files, will ask Paul for redesign this part if needed. 

@vidhya-metacell for the file uploader, is there a way to allow the user to keep uploading files once the first one(s) are loaded? 
Pretty much to enable file uploading until the user clicks Done or closes the window.

**Comment by vidhya-metacell** [comment]
@jrmartin we would need to keep the drop zone always visible for that. Currently, following the design it is hidden when user drops the files.

**Comment by zsinnema** [comment]
@jrmartin why not use the same pattern as for url dataset loading.... the files are related through the dataset id so when we have one file we can also find the other file.
May be I'm making here an assumption that is not correct... I mean for me it feels weird that I can upload a turtle file without the json. This makes no sense, or does it?

**Comment by jrmartin** [comment]
@vidhya-metacell Good to know that's possible, we overlooked this during the design and will probably have to keep the drop zone open even after uploading the first few files. 

@zsinnema Yeah, it's a bit weird that the user can upload the turtle file without the json. During the design, I thought this wouldn't be a problem since the user might want to upload the turtle file from the local system and the json from an URL, so enforcing the uploading of a json file didn't seem necessary at the time. 

One approach we can take for solving this :
1) We keep the drop zone open even after uploading the first files.
2) We enforce the upload to be one json file per one turtle file, so if the user uploads 3 turtle files then there must be 3 json files too before continuing. 

 @tgbug What do you think about enforcing this from the application? For every turtle file uploaded, there must be one json file too.

**Comment by jrmartin** [comment]
The drop zone needs to be present after loading files instead of disappearing
