### ISSUE TITLE
Define user story to filter graph by species, sex, or strains

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/sds-viewer#56]
Graph needs to have the ability to filter nodes by subject's species, sex  or strains. The user wants to be able to filter the Graph to show only those Subjects who belong to a certain specie, sex or strain.

A sparc:subject object has these as properties , which we can use to create the subjec to { specie, sex, or strain } relation.
![image.png](https://images.zenhubusercontent.com/5b8f86ce39827c509079f60a/0b51fb21-f47c-4734-8757-8fb26fd59517)

**Comment by jrmartin** [comment]
Hello @tgbugs, we expanded the user story for filtering the graph by Subject's sex, strain, species, group etc and made a few graphs mocking the filtered graphs. Can you confirm this approach works from what we discussed during the last sprint call? 

**By default, the graph is organized by Subjects.** 
![Screenshot from 2021-07-16 13-59-52](https://user-images.githubusercontent.com/4562825/126008534-4191af70-4149-421a-a6b3-08bc2808a00a.png)


 **The Graph Viewer component will have one button that opens a drop down with a set of options to filter the graph by, only one of these filters can be apply to the graph at a time.** 
![image](https://user-images.githubusercontent.com/4562825/126009878-6210e0a8-6b06-4fae-907b-8c541f2e98de.png)


**Graph filtered by Sex.** 
![Screenshot from 2021-07-16 14-00-23](https://user-images.githubusercontent.com/4562825/126008868-391e7e60-76c0-46fa-a722-f9099c3e8afb.png)


**Graph filtered by Species**
![Screenshot from 2021-07-16 14-00-49](https://user-images.githubusercontent.com/4562825/126009013-4dc3eebd-4df1-49f3-8b9c-1b4a3cb8351f.png)


**Graph filtered by Groups. In the chain of emails with Maryann, you suggested to have the Subject's group in the default hierarchy of the graph. Does this need to be way the graph is organized by default (whenever the dataset's subjects have hasAssignedGroup) with the groups on them?** 
![Screenshot from 2021-07-16 14-01-57](https://user-images.githubusercontent.com/4562825/126008904-94934ac7-f3f9-494b-8ee1-a60140ddc96b.png)

**Comment by tgbugs** [comment]
I'm not sure I would describe this as filter by, maybe group by? All the nodes should still be visible. I think the other point is that it is not the whole graph that is grouped, but sets of nodes that have the same type. So for example if I have a bunch of samples, I can repeatedly split them into groups based on the values all members have for e.g. experimental group.

The most minimal interface that I could image would be for each branch node to right clickable and show a menu to allow the predicate for the next level of grouping for leaves under that node to be selected. However, that is more complicated than it needs to be, because in all likelihood there only needs to be a single set of global rules for how to construct the hierarchy.

e.g. in some not very precise cypher (which I'm using because some of the inverse edges are missing)
0. `(award)`
1. `(dataset)<-[:TEMP:hasAwardNumber]-(award)`
    `(species)<-[:sparc:animalSubjectIsOfSpecies]-(subject)`
2. `(protocol)<-[:TEMP:hasProtocol]-(dataset)`
    `(dataset-contribution)-[:TEMP:hasDataset]->(dataset)`
    `(subject:Class{iri: "sparc:Subject"})<-[:TEMP:isAboutParticipant]-(dataset)`
3. `(sample-group)<-[:TEMP:hasAssignedGroup]-(sample)`
4. `(sample)<-[:TEMP:wasDerivedFromSubject]-(subject)`

We will have to determine how to get `sample-group` to pop in between `subject` and `sample` in this case because there is no relation between `subject` and `sample-group`. To make it a bit more complicated there is also the `species` example where we actually want `species` to be at the same level as `dataset` but not connected directly to award. So there is missing information in how way want this to be layed out, but essentially we have levels where we want certain things to appear, and we want some of them to result in the construction of new nodes in the graph when none existed before.

We are going to need this functionality even if/when we promote subject groups to be owl:NamedIndividuals because they are only connected to the individual subjects, not to the type `sparc:Subject` and also not to the dataset, so we can't just follow our nose to create the hierarchy.

**Comment by jrmartin** [comment]
@tgbugs Yeah, filter is not the right term here, 'Group By' is a better term. The 'Group By' would be so the user can group the nodes by some properties; TEMP:hasBiologicalSex , TEMP:hasAgeCategory and `sparc:animalSubjectIsOfSpecies.`

**Comment by jrmartin** [comment]
@tgbugs **Using this as the default hierarchy:** 

0. (award)
1 (dataset)<-[:TEMP:hasAwardNumber]-(award)
2 (species)<-[:sparc:animalSubjectIsOfSpecies]-(subject)
3 (protocol)<-[:TEMP:hasProtocol]-(dataset)
4 (dataset-contribution)-[:TEMP:hasDataset]->(dataset)
5 (subject:Class{iri: "sparc:Subject"})<-[:TEMP:isAboutParticipant]-(dataset)
6 (sample-group)<-[:TEMP:hasAssignedGroup]-(sample)
7 (sample)<-[:TEMP:wasDerivedFromSubject]-(subject)

**We get a graph like this** 
![ucsd sds viewer grouping - Default Hierarchy Global Rules](https://user-images.githubusercontent.com/4562825/126557810-62cbd782-5feb-404b-a359-c38350775b8b.png)

**Comment by tgbugs** [comment]
@jrmartin almost perfect. On thing that we should make sure to handled are the cases related to subjects folders when there are samples (I think we discussed this in passing, but it is not in the example, so making sure that it is documented here). The cases are:
1. subject with samples where the subjects folder contains only other folders and at most a manifest and readme.
    In this case `subject -> folder` can be left out.
2. subject folder where in addition to samples folders there are also data files at the level of the subject
    In this case `subject -> folder` should be included but should NOT include the samples subfolders which will appear under the samples further down the hierarchy.

**Comment by jrmartin** [comment]
@tgbugs Thanks , added notes for those cases :
![ucsd sds viewer grouping - Default Hierarchy Global Rules (1)](https://user-images.githubusercontent.com/4562825/126570557-e816c4d2-af8f-4aec-947b-fa9289a51200.png)
